version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: shorten
      MYSQL_ROOT_PASSWORD: foobar
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080